
server:
  port: 8101

spring:
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:3306/website_db
    username: springstudent
    password: springstudent
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
  application:
    name: PASSWORD-SERVICE
